@startuml

package "Customer Relationship managment" {
  GUI - [Customer System]
  [My app]
  [Customer System] - [My app]
}

cloud {
  [My app] --> [Customer db files] : Uses

}
[Customer db files] --> [Input/OutputStream]

[My app] --> CLI

@enduml
